# NumPy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
# MATIX
# WE NEED TO CAST THE LIST OF LIST

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
# Now we will get the 2D array
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# # arange() Function

In [11]:
# arange(start,end,step_size)
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

# # zeros() Function

To generate the arrays of all zeros

In [14]:
# 1D vector/ array
np.zeros(3)

array([0., 0., 0.])

In [15]:
# Passing tuple generates 2D arrays (rows, columns)
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# # ones() Function

To generate the arrays of all ones

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

# # linspace() Function

To generate the number of equally spaced points

In [24]:
# To generate the range from 0 to 10 equally spaced by 5
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

# # Identity Matrix

2D arrays square matrix with diagonals equals to 1

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# # random() function

random.rand() will return the number from uniform distribution i.e., 0 to 1

In [30]:
np.random.rand(10)

array([0.77160505, 0.65395683, 0.29462158, 0.73358008, 0.06706205,
       0.42220768, 0.26800352, 0.12327838, 0.24736207, 0.73154878])

In [31]:
np.random.rand(5)

array([0.71440362, 0.20967115, 0.5202398 , 0.25089376, 0.91441389])

In [33]:
# 2D array
np.random.rand(5,5)

array([[0.36250267, 0.67633209, 0.30577025, 0.73846132, 0.57582015],
       [0.46743627, 0.20139683, 0.98719942, 0.79165293, 0.79050131],
       [0.44277587, 0.65628213, 0.61480863, 0.21106991, 0.49098312],
       [0.37283815, 0.17136757, 0.55929981, 0.43586406, 0.02839704],
       [0.30467531, 0.46265803, 0.73405141, 0.48097858, 0.68748743]])

random.randn() will return the number from standard noraml distribution centering around zero

In [35]:
np.random.randn(4)

array([ 0.74941378,  0.60598347, -0.13626759, -0.1329039 ])

In [36]:
np.random.randn(4,4)

array([[-0.15884695, -0.3606564 ,  0.30886346,  0.65128327],
       [ 0.26476799,  0.06579298, -1.49795798,  1.13908905],
       [ 0.07315146,  0.47585217,  1.4718479 ,  1.04211986],
       [ 2.94262014,  1.0380068 ,  0.13121136,  0.31231122]])

random.randint() will return the single ar array of integer

In [39]:
np.random.randint(1,100)

21

In [40]:
# This will return the 10 array list within the range 1 to 100
np.random.randint(1,100,10)

array([55, 75, 39, 86, 92, 85, 69, 97, 12, 65])

# # Attributes and method of Arrays

In [41]:
arr = np.arange(25)

In [42]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
ranarr = np.random.randint(0,50,10)

In [44]:
ranarr

array([48,  6,  3, 35, 17, 45, 21,  3, 33, 31])

# ## reshape() method

returns an array containing the same data of a new shape

In [45]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
# Note:~ We can fill up only with the digit we have.
# Since arr contains 25 elements, we we could reshape it to 5*5 array
# EXAMPLE:~ ERROR CODE
# arr.reshape(5,6)

In [48]:
ranarr

array([48,  6,  3, 35, 17, 45, 21,  3, 33, 31])

# ## max() and min() method

max() will return the maximum element in an array

In [50]:
ranarr.max()

48

In [51]:
ranarr.min()

3

# ## argmax() and argmin() method

Returns the index of the max and min value

In [52]:
ranarr.argmin()

2

In [53]:
ranarr.argmax()

0

# ## shape() method

Returns the shape of the vector

In [54]:
# (25,) indicates that it's a 1D array/vector
arr.shape

(25,)

In [55]:
arr = arr.reshape(5,5)

In [56]:
arr.shape

(5, 5)

# ## Data type in an array

In [57]:
arr.dtype

dtype('int32')

Alternative way of writing random.randint() method

In [58]:
from numpy.random import randint

In [59]:
randint(2,10)

5