In [14]:
import numpy as np

In [15]:
arr = np.arange(0,11)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr[8]

8

In [18]:
arr[1:5]

array([1, 2, 3, 4])

In [19]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [20]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [21]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

numPy arrays are different from a noraml python list because their ability to braodcast

In [22]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [23]:
# Broadcasting elements
arr[0:5] = 100;

In [24]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [25]:
# we again reinitialized the array
arr = np.arange(0,11)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# # Slicing

In [27]:
slice_arr = arr[0:6]

In [28]:
slice_arr

array([0, 1, 2, 3, 4, 5])

Broadcasting the sliced array

In [29]:
slice_arr[:] = 99

In [30]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [31]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

NOTE:~ Doing slicing affect the original array as well, which means it doesn't makes the copy of the original array but it simply reflect the original array data to save the space required

If we want a copy not a reference to a original array then we do the following:

In [32]:
arr_copy = arr.copy()

In [33]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [34]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [35]:
# Broadcastng the value of arr_copy array
arr_copy[:] = 100

In [36]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [37]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# 2D Array

In [38]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [39]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [40]:
arr_2d[0][0]

5

In [41]:
# Entire row 
arr_2d[0]

array([ 5, 10, 15])

In [42]:
arr_2d[1][1]

25

OR, we can simply use the comma notation

In [43]:
arr_2d[1,1]

25

In [44]:
arr_2d[2,1]

40

Now, we want to grab :2 means rows 0 and 1. And 1: means columns 1 and 2

In [45]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [46]:
# Another example on slicing
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

# # Conditional Selection

In [47]:
arr = np.arange(1,11)

In [48]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [51]:
bool_arr = arr > 5

In [52]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [54]:
# This will return the list for which the boll_arr is True
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [55]:
# Completing the conditional selection in one line
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [56]:
arr[arr<3]

array([1, 2])

In [58]:
arr_2d_prac = np.arange(50).reshape(5,10)

In [59]:
arr_2d_prac 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [60]:
arr_2d_prac[1:3,3:5]

array([[13, 14],
       [23, 24]])